version: "3.7"

services:
  api:
    container_name: events-be
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/events-backend
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: event-db
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
