version: "3.7"

services:
  # api:
  #   image: maestro-api
  #   container_name: event-api
  #   build: .
  #   ports:
  #     - 3500:3500
  #   env_file: .env
  #   depends_on:
  #     - db

  db:
    image: postgres:11.5-alpine
    container_name: event-db
    ports:
      - 5435:5432
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
